"use client";
import {useEffect,useRef,useState} from "react";
type V={_id:string;title:string;caption:string;videoUrl:string;thumbnailUrl?:string;likes:number;views:number;shares:number;comments:{id:string;name:string;text:string}[]};
type P={displayName:string;avatarUrl:string;verified:boolean};
const fmt=(n:number)=>n>=1000000?(n/1000000).toFixed(1)+"M":n>=1000?(n/1000).toFixed(1)+"K":String(n);
export default function Videos(){
 const [items,setItems]=useState<V[]>([]),[profile,setProfile]=useState<P>({displayName:"SkanMakery",avatarUrl:"",verified:true}),[loading,setLoading]=useState(true),[comment,setComment]=useState<Record<string,string>>({});
 const refs=useRef<Record<string,HTMLVideoElement|null>>({}),seen=useRef<Set<string>>(new Set());
 useEffect(()=>{Promise.all([fetch("/api/videos").then(r=>r.json()),fetch("/api/profile").then(r=>r.json())]).then(([v,p])=>{setItems(v);setProfile(p)}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!items.length)return;const io=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target as HTMLVideoElement;if(e.isIntersecting){Object.values(refs.current).forEach(x=>{if(x&&x!==v)x.pause()});v.play().catch(()=>{});const id=v.dataset.id;if(id&&!seen.current.has(id)){seen.current.add(id);fetch("/api/videos/"+id+"/view",{method:"POST"}).then(r=>r.json()).then(x=>setItems(a=>a.map(q=>q._id===id?{...q,views:x.views}:q))).catch(()=>{})}}else v.pause()}),{threshold:.7});Object.values(refs.current).forEach(v=>v&&io.observe(v));return()=>io.disconnect()},[items]);
 const like=async(id:string)=>{const r=await fetch("/api/videos/"+id+"/like",{method:"POST"});const x=await r.json();if(r.ok)setItems(a=>a.map(v=>v._id===id?{...v,likes:x.likes}:v));else if(r.status===401)location.href="/login"};
 const share=async(v:V)=>{fetch("/api/videos/"+v._id+"/share",{method:"POST"}).catch(()=>{});const url=location.origin+"/videos#"+v._id;if(navigator.share)await navigator.share({title:v.title,url}).catch(()=>{});else await navigator.clipboard?.writeText(url)};
 const sendComment=async(v:V)=>{const text=(comment[v._id]||"").trim();if(!text)return;const r=await fetch("/api/videos/"+v._id+"/comment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(r.ok){setComment(c=>({...c,[v._id]:""}));const fresh=await fetch("/api/videos").then(r=>r.json());setItems(fresh)}};
 return <main className="reels-page"><header className="reels-top"><a href="/" className="reels-logo">Skan<span>Makery</span></a><div style={{display:"flex",gap:10,alignItems:"center"}}><a href="/profile" className="reels-login">@{profile.displayName} {profile.verified&&<span className="verified">✓</span>}</a><a href="/login" className="reels-login">Login</a></div></header>{loading?<div className="reels-loading">Loading videos…</div>:!items.length?<div className="reels-empty"><div>🎬</div><h1>No videos yet</h1><p>Videos published by SkanMakery will appear here.</p></div>:<section className="reels-feed">{items.map(v=><article className="reel" id={v._id} key={v._id}><video ref={el=>{refs.current[v._id]=el}} data-id={v._id} className="reel-video" src={v.videoUrl} poster={v.thumbnailUrl||undefined} playsInline loop muted preload="metadata"/><div className="reel-shade"/><div className="reel-info"><a href="/profile" className="reel-author"><div className="reel-avatar">{profile.avatarUrl?<img src={profile.avatarUrl} alt="" />:"S"}</div><b>@{profile.displayName} {profile.verified&&<span className="verified">✓</span>}</b><button onClick={e=>{e.preventDefault();location.href="/profile"}}>Follow</button></a><h2>{v.title}</h2><p>{v.caption}</p><span className="reel-audio">♫ Original audio · SkanMakery</span></div><aside className="reel-actions"><button onClick={()=>like(v._id)}><i>♥</i><b>{fmt(v.likes)}</b></button><button onClick={()=>document.getElementById("comments-"+v._id)?.scrollIntoView({behavior:"smooth"})}><i>💬</i><b>{fmt(v.comments?.length||0)}</b></button><button onClick={()=>share(v)}><i>↗</i><b>{fmt(v.shares)}</b></button><button onClick={()=>{const el=refs.current[v._id];if(el)el.muted=!el.muted}}><i>🔊</i></button></aside><div className="reel-comments" id={"comments-"+v._id}><input value={comment[v._id]||""} onChange={e=>setComment(c=>({...c,[v._id]:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter")sendComment(v)}} placeholder="Add a comment…"/><button onClick={()=>sendComment(v)}>Post</button></div></article>)}</section>}</main>;
}