"use client";
import {useEffect,useRef,useState} from "react";
type V={_id:string;title:string;caption:string;videoUrl:string;thumbnailUrl?:string;likes:number;views:number;shares:number;comments:{id:string;name:string;text:string}[]};
const fmt=(n:number)=>n>=1000000?(n/1000000).toFixed(1)+"M":n>=1000?(n/1000).toFixed(1)+"K":String(n);
export default function Videos(){
 const [items,setItems]=useState<V[]>([]),[loading,setLoading]=useState(true),[comment,setComment]=useState<Record<string,string>>({});
 const refs=useRef<Record<string,HTMLVideoElement|null>>({});
 useEffect(()=>{fetch("/api/videos").then(r=>r.json()).then(setItems).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!items.length)return;const io=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target as HTMLVideoElement;if(e.isIntersecting){v.play().catch(()=>{});const id=v.dataset.id;if(id)fetch("/api/videos/"+id+"/view",{method:"POST"}).then(r=>r.json()).then(x=>setItems(a=>a.map(q=>q._id===id?{...q,views:x.views}:q)));}else v.pause();}),{threshold:.65});Object.values(refs.current).forEach(v=>v&&io.observe(v));return()=>io.disconnect();},[items]);
 const like=async(id:string)=>{const r=await fetch("/api/videos/"+id+"/like",{method:"POST"}).then(x=>x.json());setItems(a=>a.map(v=>v._id===id?{...v,likes:r.likes}:v));};
 const share=async(v:V)=>{await fetch("/api/videos/"+v._id+"/share",{method:"POST"});if(navigator.share)await navigator.share({title:v.title,url:location.origin+"/videos#"+v._id}).catch(()=>{});else await navigator.clipboard?.writeText(location.origin+"/videos#"+v._id);};
 const sendComment=async(v:V)=>{const text=(comment[v._id]||"").trim();if(!text)return;await fetch("/api/videos/"+v._id+"/comment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});setComment(c=>({...c,[v._id]:""}));const fresh=await fetch("/api/videos").then(r=>r.json());setItems(fresh);};
 return <main className="reels-page"><header className="reels-top"><a href="/" className="reels-logo">Skan<span>Makery</span></a><a href="/login" className="reels-login">Login</a></header>{loading?<div className="reels-loading">Loading videos…</div>:!items.length?<div className="reels-empty"><div>🎬</div><h1>No videos yet</h1><p>Videos published by SkanMakery will appear here.</p></div>:<section className="reels-feed">{items.map(v=><article className="reel" id={v._id} key={v._id}><video ref={el=>{refs.current[v._id]=el}} data-id={v._id} className="reel-video" src={v.videoUrl} poster={v.thumbnailUrl||undefined} playsInline loop muted controls={false}/><div className="reel-shade"/><div className="reel-info"><div className="reel-author"><div className="reel-avatar">S</div><b>@SkanMakery</b><button>Follow</button></div><h2>{v.title}</h2><p>{v.caption}</p><span className="reel-audio">♫ Original audio · SkanMakery</span></div><aside className="reel-actions"><button onClick={()=>like(v._id)}><i>♥</i><b>{fmt(v.likes)}</b></button><button onClick={()=>document.getElementById("comments-"+v._id)?.scrollIntoView({behavior:"smooth"})}><i>💬</i><b>{fmt(v.comments?.length||0)}</b></button><button onClick={()=>share(v)}><i>↗</i><b>{fmt(v.shares)}</b></button><button onClick={()=>{const el=refs.current[v._id];if(el)el.muted=!el.muted}}><i>🔊</i></button></aside><div className="reel-comments" id={"comments-"+v._id}><input value={comment[v._id]||""} onChange={e=>setComment(c=>({...c,[v._id]:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter")sendComment(v)}} placeholder="Add a comment…"/><button onClick={()=>sendComment(v)}>Post</button></div></article>)}</section>}</main>;
}
