// @ts-nocheck
"use client";
import {useState} from "react";
export default function CreateScan(){
 const [form,setForm]=useState({name:"",title:"",message:"",mode:"video",camera:"front",type:"camera"}),[location,setLocation]=useState<any>(null),[result,setResult]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[locating,setLocating]=useState(false);
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));
 const useLocation=()=>{setError("");setLocating(true);if(!navigator.geolocation){setError("Your browser does not support location access.");setLocating(false);return}navigator.geolocation.getCurrentPosition(p=>{setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy});setLocating(false)},e=>{setError(e.code===1?"Location access was denied. Please allow it in your browser.":"Could not get your location. Turn on Location and try again.");setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
 const create=async()=>{setError("");setBusy(true);try{const body={...form};if(form.type==="location"){if(!location){setError("First tap “Use my current location” and allow location access.");return}body.latitude=location.latitude;body.longitude=location.longitude}const r=await fetch("/api/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok){setError(x.error||"Could not create scan");return}setResult(x)}catch{setError("Network error. Please try again.")}finally{setBusy(false)}};
 return <div className="dashboard"><aside className="side"><div className="brand">Skan<span>Makery</span></div><nav><a href="/dashboard">Dashboard</a><a className="nav-active" href="/dashboard/scans">My Scans</a><a href="/dashboard/create">＋ Create QR</a><a href="/dashboard/qrs">My QR Codes</a></nav></aside><main className="main"><div className="page-head"><span className="eyebrow">SCAN STUDIO</span><h1>Create a Scan</h1><p>Choose what the QR should do. Camera access is only requested from the person who opens a camera scan.</p></div>
 <section className="form" style={{maxWidth:820}}>
  <div className="capture-tabs"><button type="button" className={form.type==="camera"?"active":""} onClick={()=>set("type","camera")}>😈 PRANK SCAN</button><button type="button" className={form.type==="location"?"active":""} onClick={()=>set("type","location")}>📍 LOCATION</button></div>
  <div className="field"><label>Scan name</label><input value={form.name} onChange={e=>set("name",e.target.value)} placeholder="My scan" required/></div>
  <div className="field"><label>Title</label><input value={form.title} onChange={e=>set("title",e.target.value)} placeholder={form.type==="location"?"My location":"Camera capture"}/></div>
  <div className="field"><label>Message</label><textarea value={form.message} onChange={e=>set("message",e.target.value)} placeholder={form.type==="location"?"This map shows the location selected by the creator.":"Explain clearly what happens after camera permission."}/></div>
  {form.type==="location"?<div className="location-builder"><div className="location-builder-icon">📍</div><div><h3>Use my current location</h3><p>Allow your browser to access your location now. SkanMakery saves these coordinates into this scan and shows them on Google Maps to anyone who scans it.</p></div><button type="button" className="btn primary" onClick={useLocation} disabled={locating}>{locating?"Getting location…":location?"✓ Location selected":"Allow location access"}</button>{location&&<small>Coordinates captured · accuracy about {Math.round(location.accuracy||0)}m</small>}</div>:<><div className="capture-tabs"><button type="button" className={form.mode==="video"?"active":""} onClick={()=>set("mode","video")}>🎥 Video</button><button type="button" className={form.mode==="photo"?"active":""} onClick={()=>set("mode","photo")}>📸 Photo</button></div><div className="field"><label>Camera</label><select value={form.camera} onChange={e=>set("camera",e.target.value)}><option value="front">Front camera</option><option value="back">Back camera</option></select></div><div className="wifi-note"><span>🔐</span><div><b>One PRANK SCAN button</b><p>The visitor grants camera permission. No live preview or recording controls are shown after permission.</p></div></div></>}
  {error&&<p className="error">{error}</p>}<button className="btn primary create-btn" disabled={busy||!form.name.trim()|| (form.type==="location"&&!location)} onClick={create}>{busy?"Creating…":form.type==="location"?"Create Location Scan →":"Create PRANK SCAN →"}</button>
 </section>
 {result&&<section className="card" style={{maxWidth:820,marginTop:20}}><h2>Scan ready ✓</h2><p>{result.publicUrl}</p><img src={result.qrUrl} alt="Scan QR" style={{width:220,height:220,borderRadius:18}}/><p><a className="btn primary" href={result.publicUrl} target="_blank">Open Scan ↗</a></p></section>}
 </main></div>;
}