// @ts-nocheck
"use client";
import {useEffect,useMemo,useState} from "react";
export default function QrAdmin(){
 const [items,setItems]=useState<any[]>([]),[q,setQ]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);try{const r=await fetch("/api/admin/qrs");const x=await r.json();setItems(Array.isArray(x)?x:[])}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const del=async(id:string)=>{if(!confirm("Delete this QR?"))return;await fetch("/api/admin/qrs",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()};
 const filtered=useMemo(()=>items.filter(x=>(String(x.name)+" "+String(x.type)+" "+String(x.userId)).toLowerCase().includes(q.toLowerCase())),[items,q]);
 return <div className="dashboard admin-modern"><aside className="side"><div className="brand">Skan<span>Makery</span></div><nav className="admin-nav"><a className="" href="/admin">Overview</a><a className="" href="/admin/users">Users</a><a className="nav-active" href="/admin/qrs">QR Codes</a><a className="" href="/admin/scans">Scans</a><a className="" href="/admin/videos">Videos</a><a className="" href="/admin/otp">OTP / Email</a><a className="" href="/admin/settings">Settings</a><a href="/dashboard">User Dashboard</a></nav></aside><main className="main"><div className="page-head"><span className="eyebrow">QR CONTROL CENTER</span><h1>QR Library</h1><p>Inspect every QR, owner, type, scan count and public destination.</p></div><div className="cards"><div className="card"><div>Total</div><div className="stat">{items.length}</div></div><div className="card"><div>Active</div><div className="stat">{items.filter(x=>x.active!==false).length}</div></div><div className="card"><div>Total scans</div><div className="stat">{items.reduce((n,x)=>n+Number(x.scanCount||0),0)}</div></div><div className="card"><div>Media / special</div><div className="stat">{items.filter(x=>["video","image","audio","pdf","file","gallery","ussd","location","prank"].includes(x.type)).length}</div></div></div><section className="card admin-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, type or owner…"/><button className="btn light" onClick={load}>{busy?"Refreshing…":"↻ Refresh"}</button></section><div className="video-admin-list admin-list">{filtered.map(x=><article className="video-admin-card" key={x._id}><div><b>{x.name}</b><p>{x.type} · {x.active===false?"Disabled":"Active"}</p><small>Scans: {x.scanCount||0} · Owner: {x.userId||"—"} · {x.createdAt?new Date(x.createdAt).toLocaleString():"—"}</small></div><div className="admin-actions">{x.qrUrl&&<a className="btn light" href={x.qrUrl} target="_blank">Open QR</a>}<a className="btn light" href={"/q/"+x.slug} target="_blank">Open public</a><button className="btn light" onClick={()=>del(x._id)}>Delete</button></div></article>)}</div></main></div>;
}