// @ts-nocheck
"use client";
import {useEffect,useState} from "react";
export default function AdminCredits(){
 const [data,setData]=useState({users:[],orders:[],totals:{} as any}),[q,setQ]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 const load=async()=>{const r=await fetch("/api/admin/credits?q="+encodeURIComponent(q));const j=await r.json();if(r.ok)setData(j);else setMsg(j.error||"Could not load credits")};
 useEffect(()=>{load()},[]);
 async function act(userId,action,amount=0,enabled){setBusy(userId+action);setMsg("");const r=await fetch("/api/admin/credits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,action,amount,enabled})});const j=await r.json();setMsg(j.error||("Updated · balance "+(j.balance??"")));setBusy("");load();}
 return <div className="admin-shell"><aside className="admin-sidebar"><a className="admin-brand" href="/admin">Skan<span>Makery</span><small>CREDIT CONTROL</small></a><div className="admin-status"><i/> CREDIT SYSTEM ONLINE</div><nav><a href="/admin">◈ Overview</a><a href="/admin/users">♙ Users</a><a className="active" href="/admin/credits">⚡ Credits</a><a href="/admin/qrs">▦ QR Codes</a><a href="/admin/scans">⌁ Scans</a><a href="/admin/videos">▶ Videos</a><a href="/admin/otp">✉ OTP / Email</a><a href="/admin/settings">⚙ Settings</a></nav><div className="admin-side-bottom"><a href="/dashboard">↩ User workspace</a></div></aside>
 <main className="admin-main"><header className="admin-header"><div><span className="admin-kicker">SKANMAKERY / CREDITS</span><h1>Credit Command Center</h1><p>See every user's balance, add/remove/set credits, control weekly refills and inspect Cryptomus purchases.</p></div></header>
 <section className="credit-admin-stats"><article><span>TOTAL BALANCE</span><b>{Number(data.totals.balance||0)}</b></article><article><span>PURCHASED</span><b>{Number(data.totals.purchased||0)}</b></article><article><span>SPENT</span><b>{Number(data.totals.spent||0)}</b></article><article><span>ORDERS</span><b>{data.orders.length}</b></article></section>
 <section className="admin-panel"><div className="admin-panel-head"><div><span>USER BALANCES</span><h2>Credit accounts</h2></div><div className="credit-search-row"><input className="credit-admin-search" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search name or email…"/><button onClick={load}>Search</button></div></div>{msg&&<div className="admin-alert ok">{msg}</div>}
 <div className="credit-admin-list">{data.users.map(u=><article key={u._id}><div className="credit-user-main"><div className="credit-avatar">{String(u.name||u.email||"U").slice(0,1).toUpperCase()}</div><div><strong>{u.name||"Unnamed user"}</strong><small>{u.email}</small><small>{u.plan} · {u.status} · spent {u.totalSpent} · purchased {u.totalPurchased}</small></div></div><div className="credit-user-balance"><b>{u.balance}</b><span>credits</span></div><div className="credit-user-actions"><button disabled={!!busy} onClick={()=>{const n=prompt("Credits to add:","25");if(n)act(u._id,"grant",Number(n))}}>+ Add</button><button disabled={!!busy} onClick={()=>{const n=prompt("Credits to remove:","1");if(n)act(u._id,"remove",Number(n))}}>− Remove</button><button disabled={!!busy} onClick={()=>{const n=prompt("Set exact balance:",String(u.balance));if(n!==null)act(u._id,"set",Number(n))}}>Set</button><button disabled={!!busy} onClick={()=>act(u._id,"grantWeekly",25)}>+25 Weekly</button><button disabled={!!busy} onClick={()=>act(u._id,"weekly",0,!u.weeklyEnabled)}>{u.weeklyEnabled?"Pause weekly":"Enable weekly"}</button><button className="danger" disabled={!!busy} onClick={()=>confirm("Set this user's balance to 0?")&&act(u._id,"reset")}>Reset</button></div></article>)}</div></section>
 <section className="admin-panel" style={{marginTop:14}}><div className="admin-panel-head"><div><span>CRYPTOMUS</span><h2>Payment history</h2></div></div><div className="credit-order-list">{data.orders.map(o=><div key={o.id}><div><b>{o.pack}</b><small>{o.orderId} · {o.userId}</small></div><strong>{o.credits} credits · $\${o.amount}</strong><span className="order-status">{o.status}{o.credited?" · credited":""}</span></div>)}</div></section>
 </main></div>
}