"use client";
import {useEffect,useState} from "react";
type V={_id:string;title:string;caption:string;videoUrl:string;thumbnailUrl?:string;likes:number;views:number;shares:number;active:boolean};
export default function AdminVideos(){
 const [items,setItems]=useState<V[]>([]),[form,setForm]=useState({title:"",caption:"",videoUrl:"",thumbnailUrl:"",likes:"0",views:"0"}),[msg,setMsg]=useState("");
 const load=()=>fetch("/api/videos").then(r=>r.json()).then(setItems);
 useEffect(()=>{load()},[]);
 const add=async()=>{setMsg("");const r=await fetch("/api/videos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const x=await r.json();if(!r.ok){setMsg(x.error||"Failed");return}setForm({title:"",caption:"",videoUrl:"",thumbnailUrl:"",likes:"0",views:"0"});setMsg("Video published.");load()};
 const remove=async(id:string)=>{if(!confirm("Delete this video?"))return;await fetch("/api/videos/"+id,{method:"DELETE"});load()};
 return <div className="dashboard"><aside className="side"><div className="brand">Skan<span>Makery</span></div><div style={{marginTop:30}}><a href="/admin">Overview</a><a href="/admin/users">Users</a><a href="/admin/qrs">QR Codes</a><a className="nav-active" href="/admin/videos">Videos</a><a href="/admin/settings">Settings</a><a href="/dashboard">User Dashboard</a></div></aside><main className="main"><div className="page-head"><span className="eyebrow">VIDEO STUDIO</span><h1>Video Feed</h1><p>Publish vertical videos for the SkanMakery public feed.</p></div><div className="studio"><section className="form"><h2>Add video</h2><div className="field"><label>Title</label><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Amazing video"/></div><div className="field"><label>Caption</label><textarea value={form.caption} onChange={e=>setForm({...form,caption:e.target.value})} placeholder="Write a caption…"/></div><div className="field"><label>Video URL</label><input value={form.videoUrl} onChange={e=>setForm({...form,videoUrl:e.target.value})} placeholder="https://…/video.mp4"/></div><div className="field"><label>Thumbnail URL (optional)</label><input value={form.thumbnailUrl} onChange={e=>setForm({...form,thumbnailUrl:e.target.value})} placeholder="https://…/cover.jpg"/></div><div className="payment-grid"><div className="field"><label>Starting likes</label><input type="number" min="0" value={form.likes} onChange={e=>setForm({...form,likes:e.target.value})}/></div><div className="field"><label>Starting views</label><input type="number" min="0" value={form.views} onChange={e=>setForm({...form,views:e.target.value})}/></div></div>{msg&&<p className="success">{msg}</p>}<button className="btn primary create-btn" onClick={add}>Publish Video</button><p className="helper">Use a direct MP4/WebM URL. File-storage upload can be connected to R2/S3 in the next stage.</p></section><section><div className="video-admin-list">{items.map(v=><div className="video-admin-card" key={v._id}><video src={v.videoUrl} poster={v.thumbnailUrl||undefined} muted playsInline/><div><b>{v.title}</b><p>{v.caption}</p><small>♥ {v.likes} · 👁 {v.views} · ↗ {v.shares}</small></div><button className="btn light" onClick={()=>remove(v._id)}>Delete</button></div>)}</div></section></div></main></div>;
}
