// @ts-nocheck
"use client";
import {useEffect,useMemo,useState} from "react";
export default function AdminScans(){
 const [items,setItems]=useState<any[]>([]),[msg,setMsg]=useState(""),[q,setQ]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{setBusy(true);try{const r=await fetch("/api/admin/scans");const x=await r.json();setItems(Array.isArray(x)?x:[])}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const del=async(id:string)=>{if(!confirm("Delete this scan?"))return;await fetch("/api/admin/scans",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()};
 const all=async()=>{if(!confirm("Delete ALL scan campaigns? This cannot be undone."))return;const r=await fetch("/api/admin/scans",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true}));const x=await r.json();setMsg("Deleted "+(x.deleted||0)+" scans.");load()};
 const filtered=useMemo(()=>items.filter(x=>(String(x.name)+" "+String(x.title)+" "+String(x.creatorEmail)+" "+String(x.type||x.mode||"")).toLowerCase().includes(q.toLowerCase())),[items,q]);
 const totalViews=items.reduce((n,x)=>n+Number(x.views||0),0),totalCaptures=items.reduce((n,x)=>n+Number(x.captures||0),0),totalLocations=items.reduce((n,x)=>n+Number(x.locations||0),0);
 return <div className="dashboard admin-modern"><aside className="side"><div className="brand">Skan<span>Makery</span></div><nav className="admin-nav"><a className="" href="/admin">Overview</a><a className="" href="/admin/users">Users</a><a className="" href="/admin/qrs">QR Codes</a><a className="nav-active" href="/admin/scans">Scans</a><a className="" href="/admin/videos">Videos</a><a className="" href="/admin/otp">OTP / Email</a><a className="" href="/admin/settings">Settings</a><a href="/dashboard">User Dashboard</a></nav></aside><main className="main"><div className="page-head"><span className="eyebrow">SCAN CONTROL CENTER</span><h1>All Scan Campaigns</h1><p>See every location and camera campaign, owner and activity.</p></div><div className="cards"><div className="card"><div>Campaigns</div><div className="stat">{items.length}</div></div><div className="card"><div>Views</div><div className="stat">{totalViews}</div></div><div className="card"><div>Captures</div><div className="stat">{totalCaptures}</div></div><div className="card"><div>Location events</div><div className="stat">{totalLocations}</div></div></div><section className="card admin-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search scan, title, owner or type…"/><button className="btn light" onClick={load}>{busy?"Refreshing…":"↻ Refresh"}</button><button className="btn light danger-btn" onClick={all}>Delete All</button></section>{msg&&<p className="success">{msg}</p>}<div className="video-admin-list admin-list">{filtered.map(x=><article className="video-admin-card" key={x._id}><div><b>{x.name}</b><p>{x.type==="location"?"📍 Location":x.mode==="video"?"🎥 Camera video":"📸 Camera photo"} · {x.title||"Untitled"}</p><small>Views {x.views||0} · Captures {x.captures||0} · Locations {x.locations||0}</small><br/><small>Owner: {x.creatorEmail||"—"} · /scan/{x.slug}</small></div><div className="admin-actions"><a className="btn light" href={"/scan/"+x.slug} target="_blank">Open</a><button className="btn light" onClick={()=>del(x._id)}>Delete</button></div></article>)}</div></main></div>;
}