// @ts-nocheck
"use client";
import {useEffect,useState} from "react";
export default function AdminScans(){
 const [items,setItems]=useState<any[]>([]),[msg,setMsg]=useState(""),[q,setQ]=useState("");
 const load=()=>fetch("/api/admin/scans").then(r=>r.json()).then(x=>setItems(Array.isArray(x)?x:[]));useEffect(load,[]);
 const del=async(id:string)=>{if(!confirm("Delete this scan?"))return;await fetch("/api/admin/scans",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()};
 const all=async()=>{if(!confirm("Delete all scan campaigns?"))return;const r=await fetch("/api/admin/scans",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})});const x=await r.json();setMsg("Deleted "+(x.deleted||0)+" scans.");load()};
 const filtered=items.filter(x=>(x.name+" "+x.title+" "+x.creatorEmail+" "+(x.type||x.mode||"")).toLowerCase().includes(q.toLowerCase()));
 const totalViews=items.reduce((n,x)=>n+Number(x.views||0),0),totalCaptures=items.reduce((n,x)=>n+Number(x.captures||0),0),totalLocations=items.reduce((n,x)=>n+Number(x.locations||0),0);
 return <div className="dashboard"><aside className="side"><div className="brand">Skan<span>Makery</span></div><div style={{marginTop:30}}><a href="/admin">Overview</a><a href="/admin/users">Users</a><a href="/admin/qrs">QR Codes</a><a className="nav-active" href="/admin/scans">Scans</a><a href="/admin/videos">Videos</a><a href="/admin/otp">OTP / Email</a><a href="/admin/settings">Settings</a></div></aside><main className="main"><div className="page-head"><span className="eyebrow">SCAN CONTROL CENTER</span><h1>All Scans</h1><p>Monitor scan campaigns, owners and activity.</p></div><div className="cards"><div className="card"><div>Campaigns</div><div className="stat">{items.length}</div></div><div className="card"><div>Views</div><div className="stat">{totalViews}</div></div><div className="card"><div>Captures</div><div className="stat">{totalCaptures}</div></div><div className="card"><div>Location events</div><div className="stat">{totalLocations}</div></div></div><section className="card" style={{marginTop:20,display:"flex",gap:10,flexWrap:"wrap"}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search scan, owner, type…" style={{flex:1,minWidth:220}}/><button className="btn light" onClick={all}>Delete All Scans</button></section>{msg&&<p className="success">{msg}</p>}<div className="video-admin-list" style={{marginTop:18}}>{filtered.map(x=><div className="video-admin-card" key={x._id}><div><b>{x.name}</b><p>{x.title||x.message}</p><small>Type: {x.type||x.mode||"—"} · Views: {x.views||0} · Captures: {x.captures||0} · Locations: {x.locations||0}</small><br/><small>Owner: {x.creatorEmail||"No email"} · /scan/{x.slug}</small></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><a className="btn light" href={"/scan/"+x.slug} target="_blank">View</a><button className="btn light" onClick={()=>del(x._id)}>Delete</button></div></div>)}</div></main></div>