"use client";
import {useState} from "react";
const types=[["url","🔗","Website"],["text","📝","Text"],["phone","📞","Phone"],["ussd","💳","USSD Payment"],["email","✉️","Email"],["whatsapp","💬","WhatsApp"],["wifi","📶","Wi‑Fi"],["location","📍","Location"],["contact","👤","Contact"]];
export default function Create(){
 const [type,setType]=useState("url"),[name,setName]=useState(""),[value,setValue]=useState(""),[phone,setPhone]=useState(""),[prefix,setPrefix]=useState("*883*"),[amount,setAmount]=useState(""),[qr,setQr]=useState(""),[publicUrl,setPublicUrl]=useState(""),[error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/qr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,type,value,phone,ussdPrefix:prefix,amount})});const d=await r.json();if(!r.ok){setError(d.error||"Failed");return}setQr(d.qrUrl);setPublicUrl(d.publicUrl)}
 const ussdPreview=type==="ussd"?prefix+(phone||"7801020")+"*"+(amount||"10")+"#":"";
 return <div className="dashboard"><aside className="side"><div className="brand">Skan<span>Makery</span></div><nav><a href="/dashboard">Dashboard</a><a className="nav-active" href="/dashboard/create">＋ Create QR</a><a href="/dashboard/qrs">My QR Codes</a></nav></aside>
 <main className="main"><div className="page-head"><div><span className="eyebrow">QR STUDIO</span><h1>Create something scannable</h1><p>Choose an action. Your QR opens the destination directly after scanning.</p></div></div>
 <div className="type-grid">{types.map(([id,icon,label])=><button type="button" className={"type-card "+(type===id?"active":"")} onClick={()=>setType(id)} key={id}><span>{icon}</span><b>{label}</b><small>{id==="url"?"Open a website":id==="ussd"?"Number + amount":id==="phone"?"Open phone dialer":"Create QR"}</small></button>)}</div>
 <div className="studio"><form className="form" onSubmit={submit}><div className="field"><label>QR Name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. My Payment QR" required/></div>
 {type==="ussd"?<><div className="field"><label>USSD Code</label><input value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="*883*" required/></div><div className="field"><label>Customer Number</label><input inputMode="numeric" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="7801020" required/></div><div className="field"><label>Amount</label><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="10" required/><small className="preview">Preview: <b>{ussdPreview}</b></small></div></>:type==="phone"?<div className="field"><label>Phone Number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+2517801020" required/></div>:<div className="field"><label>{type==="url"?"Website URL":type==="text"?"Text / Message":"Value"}</label><textarea rows={type==="text"?6:3} value={value} onChange={e=>setValue(e.target.value)} placeholder={type==="url"?"https://example.com":"Enter your content..."} required/></div>}
 {error&&<p className="error">{error}</p>}<button className="btn primary create-btn">Generate QR →</button></form>
 {qr&&<div className="result-card"><div className="success">✓ QR created</div><img className="qr-image" src={qr}/><p className="public-url">{publicUrl}</p><div className="result-actions"><a className="btn primary" href={publicUrl} target="_blank">Test Scan ↗</a><button className="btn light" onClick={()=>window.print()}>🖨 Print QR</button></div></div>}</div></main></div>
}